name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop
  workflow_dispatch:

concurrency:
  group: ${{github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  validate:
    uses: ./.github/workflows/reusable_automated_tests.yaml
    secrets:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      