name: CD (Deploy to Production)

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  validate:
    uses: ./.github/workflows/reusable_automated_tests.yaml
    secrets:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  deploy:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Application to Production
        env:
          DEPLOY_SERVER_SSH_PEM: ${{ secrets.DEPLOY_SERVER_SSH_PEM }}
          TAG: ${{ github.ref_name }}
        run: |
          echo Deploy $TAG
          echo "$DEPLOY_SERVER_SSH_PEM" > deploy_key.pem
          chmod 400 deploy_key.pem
          ssh -o StrictHostKeyChecking=no -i deploy_key.pem ubuntu@13.228.40.10 'bash -s' < ./scripts/deploy.sh "$TAG"